/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as CheckoutIdRouteImport } from './routes/checkout.$id'
import { Route as FnbIdRouteImport } from './routes/fnb.$id'
import { Route as SeatsIdRouteImport } from './routes/seats.$id'
import { Route as ShowtimesIdRouteImport } from './routes/showtimes.$id'
import { Route as TicketRefRouteImport } from './routes/ticket.$ref'
import { Route as TitleIdRouteImport } from './routes/title.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutIdRoute = CheckoutIdRouteImport.update({
  id: '/checkout/$id',
  path: '/checkout/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const FnbIdRoute = FnbIdRouteImport.update({
  id: '/fnb/$id',
  path: '/fnb/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SeatsIdRoute = SeatsIdRouteImport.update({
  id: '/seats/$id',
  path: '/seats/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowtimesIdRoute = ShowtimesIdRouteImport.update({
  id: '/showtimes/$id',
  path: '/showtimes/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketRefRoute = TicketRefRouteImport.update({
  id: '/ticket/$ref',
  path: '/ticket/$ref',
  getParentRoute: () => rootRouteImport,
} as any)
const TitleIdRoute = TitleIdRouteImport.update({
  id: '/title/$id',
  path: '/title/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/explore': typeof ExploreRoute
  '/profile': typeof ProfileRoute
  '/checkout/$id': typeof CheckoutIdRoute
  '/fnb/$id': typeof FnbIdRoute
  '/seats/$id': typeof SeatsIdRoute
  '/showtimes/$id': typeof ShowtimesIdRoute
  '/ticket/$ref': typeof TicketRefRoute
  '/title/$id': typeof TitleIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/explore': typeof ExploreRoute
  '/profile': typeof ProfileRoute
  '/checkout/$id': typeof CheckoutIdRoute
  '/fnb/$id': typeof FnbIdRoute
  '/seats/$id': typeof SeatsIdRoute
  '/showtimes/$id': typeof ShowtimesIdRoute
  '/ticket/$ref': typeof TicketRefRoute
  '/title/$id': typeof TitleIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/explore': typeof ExploreRoute
  '/profile': typeof ProfileRoute
  '/checkout/$id': typeof CheckoutIdRoute
  '/fnb/$id': typeof FnbIdRoute
  '/seats/$id': typeof SeatsIdRoute
  '/showtimes/$id': typeof ShowtimesIdRoute
  '/ticket/$ref': typeof TicketRefRoute
  '/title/$id': typeof TitleIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/explore'
    | '/profile'
    | '/checkout/$id'
    | '/fnb/$id'
    | '/seats/$id'
    | '/showtimes/$id'
    | '/ticket/$ref'
    | '/title/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/explore'
    | '/profile'
    | '/checkout/$id'
    | '/fnb/$id'
    | '/seats/$id'
    | '/showtimes/$id'
    | '/ticket/$ref'
    | '/title/$id'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/explore'
    | '/profile'
    | '/checkout/$id'
    | '/fnb/$id'
    | '/seats/$id'
    | '/showtimes/$id'
    | '/ticket/$ref'
    | '/title/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ExploreRoute: typeof ExploreRoute
  ProfileRoute: typeof ProfileRoute
  CheckoutIdRoute: typeof CheckoutIdRoute
  FnbIdRoute: typeof FnbIdRoute
  SeatsIdRoute: typeof SeatsIdRoute
  ShowtimesIdRoute: typeof ShowtimesIdRoute
  TicketRefRoute: typeof TicketRefRoute
  TitleIdRoute: typeof TitleIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/$id': {
      id: '/checkout/$id'
      path: '/checkout/$id'
      fullPath: '/checkout/$id'
      preLoaderRoute: typeof CheckoutIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fnb/$id': {
      id: '/fnb/$id'
      path: '/fnb/$id'
      fullPath: '/fnb/$id'
      preLoaderRoute: typeof FnbIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seats/$id': {
      id: '/seats/$id'
      path: '/seats/$id'
      fullPath: '/seats/$id'
      preLoaderRoute: typeof SeatsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/showtimes/$id': {
      id: '/showtimes/$id'
      path: '/showtimes/$id'
      fullPath: '/showtimes/$id'
      preLoaderRoute: typeof ShowtimesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ticket/$ref': {
      id: '/ticket/$ref'
      path: '/ticket/$ref'
      fullPath: '/ticket/$ref'
      preLoaderRoute: typeof TicketRefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/title/$id': {
      id: '/title/$id'
      path: '/title/$id'
      fullPath: '/title/$id'
      preLoaderRoute: typeof TitleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ExploreRoute: ExploreRoute,
  ProfileRoute: ProfileRoute,
  CheckoutIdRoute: CheckoutIdRoute,
  FnbIdRoute: FnbIdRoute,
  SeatsIdRoute: SeatsIdRoute,
  ShowtimesIdRoute: ShowtimesIdRoute,
  TicketRefRoute: TicketRefRoute,
  TitleIdRoute: TitleIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
